apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage-deploy
  labels:
    app: myimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage-container
        image: docker.io/vishu2498/myimage:v1
        ports:
        - containerPort: 80